### PR TITLE
added c++ solution to the problem no - 1832

### PR DESCRIPTION
**Pull request by snehel4510**

### CODE REVIEW

**Comment by luliyucoordinate** [comment]
Please format your code and add the necessary spaces and line breaks

**Comment by snehel4510** [comment]
Could you please elaborate on what else are you asking for?
Here is the code that i have commited and I guess it's perfectly formatted...
image

**Comment by luliyucoordinate** [comment]
https://google.github.io/styleguide/cppguide.html#Conditionals

**Comment by snehel4510** [comment]
Thanks for providing the reference. I have formatted my code and have added the necessary spaces and line breaks. Kindly review and merge my PR.

**Comment by luliyucoordinate** [comment]
thx, LGTM

**Pull request merged**
